# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# This file contains test-specific overrides for the base configuration

# Dock test overrides
docks:
  map:
    docks:
      - dock_id: dock01
        dock_type: nova_carter_dock
        dock_pose:
          x: 9.026
          y: 9.212
          yaw: 0
          staging_offset: 0
      - dock_id: dock02
        dock_type: nova_carter_dock
        dock_pose:
          x: 8.908
          y: 35.336
          yaw: 0
          staging_offset: 0
      - dock_id: dock03
        dock_type: nova_carter_dock
        dock_pose:
          x: 28.942
          y: 19.17
          yaw: 0
          staging_offset: 0

# Galileo Hubble test overrides
galileo_hubble:
  map:
    map_file: "/config/maps/nvidia_galileo_hubble.png"
    metadata:
      map_id: "galileo_hubble"
      resolution: 0.05
      occupancy_threshold: 206
    docks:
      - dock_id: dock01
        dock_type: nova_carter_dock
        dock_pose:
          x: 43.7278
          y: 19.7377
          yaw: 1.36224
      
# S3 map test overrides
map_file_s3:
  map:
    map_file: null
    map_s3: s3://maps/augmented_map.png
    metadata_yaml: /config/test_map_s3_metadata.yaml
    metadata:
      map_id: "galileo_hubble"
      resolution: 0.05
      occupancy_threshold: 129
      x_offset: 1000.0
      y_offset: 1000.0
    docks:
      - dock_id: dock01
        dock_type: nova_carter_dock
        dock_pose:
          x: 43.7278
          y: 19.7377
          yaw: 1.36224

# Robots test overrides
robots:
  robots:
    - name: "robot_a"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30
      battery:
        critical_level: 15
        recommended_minimum: 20
        recommended_maximum: 80
    - name: "robot_b"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30
      battery:
        recommended_minimum: 30
    - name: "robot_c"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30

# Pick and place test overrides
pickplace:
  robots:
    - name: "robot_a"
      labels: ["test", "MANIPULATOR", "ros"]
      heartbeat_timeout: 30
    - name: "robot_b"
      labels: ["test", "CARRIER", "ros"]
      heartbeat_timeout: 30
      battery:
        recommended_minimum: 30
    - name: "robot_c"
      labels: ["test", "MANIPULATOR", "ros"]
      heartbeat_timeout: 30
