# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# This file contains test-specific overrides for the base configuration

# Dock test overrides
docks:
  map:
    docks:
      - dock_id: dock01
        dock_type: nova_carter_dock
        dock_pose:
          x: 9.026
          y: 9.212
          yaw: 0
          staging_offset: 0
      - dock_id: dock02
        dock_type: nova_carter_dock
        dock_pose:
          x: 8.908
          y: 35.336
          yaw: 0
          staging_offset: 0
      - dock_id: dock03
        dock_type: nova_carter_dock
        dock_pose:
          x: 28.942
          y: 19.17
          yaw: 0
          staging_offset: 0

# Galileo Hubble test overrides
galileo_hubble:
  map:
    map_file: "/config/maps/nvidia_galileo_hubble.png"
    metadata:
      map_id: "galileo_hubble"
      resolution: 0.05
      occupancy_threshold: 206
    docks:
      - dock_id: dock01
        dock_type: nova_carter_dock
        dock_pose:
          x: 43.7278
          y: 19.7377
          yaw: 1.36224
      
# Semantic map test overrides
map_file_semantic:
  map:
    map_file: "/config/maps/elevator_office_1_semantic_map.json"
    metadata:
      map_id: "elevator_office"

# Semantic map with dock test overrides
map_file_semantic_with_dock:
  map:
    map_file: "/config/maps/galileo_with_docking_station_semantic_map.json"
    metadata:
      map_id: "galileo"
    docks:
      - dock_id: dock01
        dock_type: nova_carter_dock
        dock_pose:
          x: 3.446205
          y: 9.7845
          yaw: 0

# Robots test overrides
robots:
  robots:
    - name: "robot_a"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30
      battery:
        critical_level: 15
        recommended_minimum: 20
        recommended_maximum: 80
    - name: "robot_b"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30
      battery:
        recommended_minimum: 30
    - name: "robot_c"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30

# Pick and place test overrides
pickplace:
  robots:
    - name: "robot_a"
      labels: ["test", "arm", "ros"]
      heartbeat_timeout: 30
      battery:
        critical_level: 15
        recommended_minimum: 20
        recommended_maximum: 80
    - name: "robot_b"
      labels: ["test", "carter", "ros"]
      heartbeat_timeout: 30
      battery:
        recommended_minimum: 30
    - name: "robot_c"
      labels: ["test", "arm", "ros"]
      heartbeat_timeout: 30 