{{- if .Values.enableChart }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mission-control.fullname" . }}-config
  labels:
    {{- include "mission-control.labels" . | nindent 4 }}
data:
  defaults.yaml: |-
    robots:
      {{- range .Values.env.robots }}
      - name: "{{ .name }}"
        labels:
          {{- range .labels }}
          - {{.}}
          {{- end}}
        heartbeat_timeout: {{ .heartbeat_timeout }}
        battery:
          critical_level: {{ .battery.critical_level }}
          recommended_minimum: {{ .battery.recommended_minimum }}
          recommended_maximum: {{ .battery.recommended_maximum }}
      {{- end }}

    services:
      waypoint_graph:
        base_url: "{{ if .Values.waypointGraphGenerator.enabled }}http://{{ include "mission-control.fullname" . }}-wpg:80{{ else }}{{ .Values.waypointGraphGenerator.externalServiceUrl }}{{ end }}"
      mission_database:
        base_url: "{{ .Values.missionDatabase.externalServiceUrl }}"
      mission_dispatch:
        base_url: "{{ .Values.missionDispatch.externalServiceUrl }}"
        default_mission_timeout: {{ .Values.missionDispatch.mission_timeout }}
      cuopt:
        base_url: "{{ if .Values.cuopt.enabled }}http://{{ include "mission-control.fullname" . }}-cuopt:80{{ else }}{{ .Values.cuopt.externalServiceUrl }}{{ end }}"
        solve_parameters:
          time_limit: .5
          verbose_mode: False

    map:
      map_file: "{{ .Values.env.map.file }}"
      map_uri: "{{ .Values.env.map.uri }}"
      map_s3: "{{ .Values.env.map.s3 }}"
      metadata_yaml: "{{ .Values.env.map.metadataYaml }}"
      metadata:
        map_id: "{{ .Values.env.map.id }}"
        resolution: {{ .Values.env.map.resolution }}
        occupancy_threshold: {{ .Values.env.map.occupancyThreshold }}
        x_offset: {{ .Values.env.map.x_offset }}
        y_offset: {{ .Values.env.map.y_offset }}
        rotation: {{ .Values.env.map.rotation }}
        safety_distance: {{ .Values.env.map.safety_distance }}
      push_map_on_startup: {{ .Values.env.map.pushMapOnStartup }}
      save_route_visualization: {{ .Values.env.map.saveRouteVisualization }}
      docks:
        {{- range .Values.env.map.docks }}
        - dock_id: {{ .dockId }}
          dock_type: {{ .dockType }}
          dock_pose:
            x: {{ .dockPose.xCoordinate }}
            y: {{ .dockPose.yCoordinate }}
            yaw: {{ .dockPose.yaw }}
        {{- end }}

    constants:
      MIN_BATTERY: {{ .Values.env.constants.minBattery }}
      STARTUP_TIMEOUT: {{ .Values.env.constants.startupTimeout }}

    telemetry:
      SEND_TELEMETRY: {{ .Values.env.telemetry.enabled }}
      TELEMETRY_ID: {{ .Values.env.telemetry.id }}
      TELEMETRY_SECRET: {{ .Values.env.telemetry.secret }}
      TELEMETRY_ENV: {{ .Values.env.telemetry.env }}

    s3:
      AWS_ACCESS_KEY_ID: {{ .Values.env.s3.accessKey }}
      AWS_SECRET_ACCESS_KEY: {{ .Values.env.s3.secretKey }}
      AWS_REGION: {{ .Values.env.s3.region }}
      AWS_ENDPOINT_URL: {{ .Values.env.s3.endpointUrl }}
{{- end }}