{{- if .Values.enableChart }}
{{- if .Values.waypointGraphGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mission-control.fullname" . }}-wpg
  labels:
    {{- include "mission-control.waypointGraphGenerator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.waypointGraphGenerator.replicaCount }}
  selector:
    matchLabels:
      {{- include "mission-control.waypointGraphGenerator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mission-control.waypointGraphGenerator.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "mission-control.fullname" . }}-wpg
        image: "{{ .Values.waypointGraphGenerator.image.repository }}:{{ .Values.waypointGraphGenerator.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.waypointGraphGenerator.image.pullPolicy }}
        command: ["python"]
        args: 
        - "scripts/rest_api.py"
        # volumeMounts:
        #   - name: conf-volume
        #     mountPath: /tmp/config
        #   - name: deepmap-conf-file
        #     mountPath: /tmp/config/etc/api_public_config.pb.txt
        #     subPath: api_public_config.pb.txt
        #   - name: vehicle-conf-file
        #     mountPath: /tmp/config/etc/vehicle_info.pb.txt
        #     subPath: vehicle_info.pb.txt
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.waypointGraphGenerator.limits.cpu }}
            memory: {{ .Values.resources.waypointGraphGenerator.limits.memory }}
            nvidia.com/gpu: {{ .Values.resources.waypointGraphGenerator.limits.gpu }}
          requests:
            cpu: {{ .Values.resources.waypointGraphGenerator.requests.cpu }}
            memory: {{ .Values.resources.waypointGraphGenerator.requests.memory }}
            nvidia.com/gpu: {{ .Values.resources.waypointGraphGenerator.requests.gpu }}
{{- end }}
{{- end }}