{{- if .Values.enableChart }}
{{- if .Values.waypointGraphGenerator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "mission-control.fullname" . }}-wpg
  labels:
    {{- include "mission-control.waypointGraphGenerator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: wpg-port
  selector:
    {{- include "mission-control.waypointGraphGenerator.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}